# Generated by Django 4.0.8 on 2026-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelevel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
