# Generated by Django 2.2.19 on 2021-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
