# Generated by Django 2.2.19 on 2021-06-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_migrate_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='month',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='year',
        ),
    ]
