# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdcounter', '0002_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('sort_key',), 'verbose_name': 'autor', 'verbose_name_plural': 'autorzy'},
        ),
        migrations.AlterModelOptions(
            name='bookstub',
            options={'ordering': ('title',), 'verbose_name': 'zapowiedź książki', 'verbose_name_plural': 'zapowiedzi książek'},
        ),
        migrations.AlterField(
            model_name='author',
            name='death',
            field=models.IntegerField(blank=True, null=True, verbose_name='rok śmierci'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sort_key',
            field=models.CharField(db_index=True, max_length=120, verbose_name='klucz sortowania'),
        ),
        migrations.AlterField(
            model_name='bookstub',
            name='author',
            field=models.CharField(max_length=120, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='bookstub',
            name='pd',
            field=models.IntegerField(blank=True, null=True, verbose_name='trafia do domeny publicznej'),
        ),
        migrations.AlterField(
            model_name='bookstub',
            name='title',
            field=models.CharField(max_length=120, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='bookstub',
            name='translator',
            field=models.TextField(blank=True, verbose_name='tłumacz'),
        ),
    ]
