# Generated by Django 4.0.8 on 2026-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdcounter', '0003_alter_author_options_alter_bookstub_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sort_key',
            field=models.CharField(db_collation='C', db_index=True, max_length=120, verbose_name='klucz sortowania'),
        ),
    ]
