# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isbn', '0004_auto_20180215_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onixrecord',
            name='isbn_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isbn.ISBNPool'),
        ),
    ]
