# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='sponsorpage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='sponsorpage',
            name='sponsors',
            field=models.TextField(default='{}', verbose_name='sponsorzy'),
        ),
    ]
