# Generated by Django 4.0.8 on 2023-08-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0002_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'info page', 'verbose_name_plural': 'info pages'},
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='main_page',
        ),
    ]
