# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0003_alter_infopage_options_remove_infopage_main_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'strona informacyjna', 'verbose_name_plural': 'strony informacyjne'},
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column',
            field=models.TextField(blank=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_de',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_en',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_es',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_fr',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_it',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_lt',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_pl',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_ru',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='left_column_uk',
            field=models.TextField(blank=True, null=True, verbose_name='lewa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column',
            field=models.TextField(blank=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_de',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_en',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_es',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_fr',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_it',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_lt',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_pl',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_ru',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='right_column_uk',
            field=models.TextField(blank=True, null=True, verbose_name='prawa kolumna'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_es',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_it',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_lt',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_pl',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
    ]
