# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'ankieta', 'verbose_name_plural': 'ankiety'},
        ),
        migrations.AlterModelOptions(
            name='pollitem',
            options={'verbose_name': 'pozycja ankiety', 'verbose_name_plural': 'pozycje ankiety'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='open',
            field=models.BooleanField(default=False, verbose_name='otwarta'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='pollitem',
            name='content',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='pollitem',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='licznik głosów'),
        ),
    ]
