# Generated by Django 2.2.27 on 2022-09-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0002_auto_20151221_1225'),
        ('chunks', '0003_auto_20151221_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_it', models.CharField(blank=True, max_length=255, null=True)),
                ('name_lt', models.CharField(blank=True, max_length=255, null=True)),
                ('name_pl', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('highlight', models.BooleanField()),
                ('infopage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infopages.InfoPage')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunks.Menu')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
