# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0004_menu_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('key',), 'verbose_name': 'załącznik', 'verbose_name_plural': 'załączniki'},
        ),
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ('key',), 'verbose_name': 'kawałek', 'verbose_name_plural': 'kawałki'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='key',
            field=models.CharField(help_text='Unikalna nazwa dla tego załącznika', max_length=255, primary_key=True, serialize=False, verbose_name='klucz'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content',
            field=models.TextField(blank=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_de',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_es',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_fr',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_it',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_lt',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_pl',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content_uk',
            field=models.TextField(blank=True, null=True, verbose_name='zawartość'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='key',
            field=models.CharField(help_text='Unikalna nazwa dla tego kawałka treści', max_length=255, primary_key=True, serialize=False, verbose_name='klucz'),
        ),
    ]
