# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20190318_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cite',
            options={'ordering': ('vip', 'text'), 'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
    ]
