# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20190715_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='background_plain',
            field=models.BooleanField(default=False, verbose_name='plain background'),
        ),
    ]
