# Generated by Django 2.1.11 on 2019-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_cite_background_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cite',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='cite',
            name='image_shift',
        ),
        migrations.AlterField(
            model_name='cite',
            name='image',
            field=models.ImageField(blank=True, help_text='Best background is 975 x 315 px and under 100kB.', null=True, upload_to='social/cite', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='background author'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_license',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='background license name'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_license_link',
            field=models.URLField(blank=True, null=True, verbose_name='background license link'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='background link'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='background title'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture',
            field=models.ImageField(blank=True, help_text='Najlepsze wymiary: 975 x 315 z tekstem, 487 x 315 bez tekstu.', upload_to='', verbose_name='picture'),
        ),
    ]
