# Generated by Django 2.2.16 on 2021-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20190807_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'carousel', 'verbose_name_plural': 'carousels'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'español'), ('fr', 'français'), ('it', 'italiano'), ('lt', 'lietuvių'), ('pl', 'polski'), ('ru', 'русский'), ('uk', 'українська')], default='', max_length=2, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(choices=[('main', 'main')], verbose_name='placement'),
        ),
    ]
