# Generated by Django 2.2.16 on 2021-01-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20210120_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='slug',
            new_name='placement',
        ),
    ]
