# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_alter_book_options_alter_bookmedia_options_and_more'),
        ('social', '0015_alter_carousel_placement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannergroup',
            options={'ordering': ('name',), 'verbose_name': 'grupa bannerów', 'verbose_name_plural': 'grupy bannerów'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'karuzela', 'verbose_name_plural': 'karuzele'},
        ),
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ('order',), 'verbose_name': 'element karuzeli', 'verbose_name_plural': 'elementy karuzeli'},
        ),
        migrations.AlterModelOptions(
            name='cite',
            options={'ordering': ('vip', 'text'), 'verbose_name': 'banner', 'verbose_name_plural': 'bannery'},
        ),
        migrations.AlterField(
            model_name='bannergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzona'),
        ),
        migrations.AlterField(
            model_name='bannergroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'español'), ('fr', 'français'), ('it', 'italiano'), ('lt', 'lietuvių'), ('pl', 'polski'), ('ru', 'русский'), ('uk', 'українська')], default='', max_length=2, verbose_name='język'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='placement',
            field=models.SlugField(choices=[('main', 'main'), ('main_2022', 'main 2022')], verbose_name='miejsce'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='priorytet'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='banner_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.bannergroup', verbose_name='grupa bannerów'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.carousel', verbose_name='karuzela'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='kolejność'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='background_color',
            field=models.CharField(blank=True, max_length=32, verbose_name='kolor tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='background_plain',
            field=models.BooleanField(default=False, verbose_name='jednobarwne tło'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.book', verbose_name='książka'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzony'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.bannergroup', verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image',
            field=models.ImageField(blank=True, help_text='Najlepsze tło ma wielkość 975 x 315 px i waży poniżej 100kB.', null=True, upload_to='social/cite', verbose_name='obraz tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='autor obrazu tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_license',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwa licencji obrazu tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_license_link',
            field=models.URLField(blank=True, null=True, verbose_name='adres licencji obrazu tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='link obrazu tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tytuł obrazu tła'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='link',
            field=models.URLField(verbose_name='odnośnik'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture',
            field=models.ImageField(blank=True, help_text='Najlepsze wymiary: 975 x 315 z tekstem, 487 x 315 bez tekstu.', upload_to='', verbose_name='ilustracja'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='alternatywny tekst ilustracji'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='autor ilustracji'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture_license',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwa licencji ilustracji'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture_license_link',
            field=models.URLField(blank=True, null=True, verbose_name='adres licencji ilustracji'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture_link',
            field=models.URLField(blank=True, null=True, verbose_name='link ilustracji'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='picture_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tytuł ilustracji'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='small',
            field=models.BooleanField(default=False, help_text='Sprawia, że cytat wyświetla się mniejszym fontem.', verbose_name='mały'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='sticky',
            field=models.BooleanField(db_index=True, default=False, help_text='Przyklejone cytaty mają pierwszeństwo.', verbose_name='przyklejony'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='text',
            field=models.TextField(blank=True, verbose_name='tekst'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='video',
            field=models.URLField(blank=True, verbose_name='wideo'),
        ),
    ]
