# Generated by Django 4.0.8 on 2025-05-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_book_html_nonotes_file_book_html_nonotes_file_etag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0017_userconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_mode', models.CharField(choices=[('text', 'text'), ('audio', 'audio')], max_length=64)),
                ('text_percent', models.FloatField(blank=True, null=True)),
                ('text_anchor', models.CharField(blank=True, max_length=64)),
                ('audio_percent', models.FloatField(blank=True, null=True)),
                ('audio_timestamp', models.FloatField(blank=True, null=True)),
                ('implicit_text_percent', models.FloatField(blank=True, null=True)),
                ('implicit_text_anchor', models.CharField(blank=True, max_length=64)),
                ('implicit_audio_percent', models.FloatField(blank=True, null=True)),
                ('implicit_audio_timestamp', models.FloatField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
