# Generated by Django 4.0.8 on 2025-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
