# Generated by Django 4.0.8 on 2025-07-22 13:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_move_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='reported_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='reported_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlistitem',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
