# Generated by Django 4.0.8 on 2025-07-22 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20250722_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
