# Generated by Django 4.0.8 on 2025-07-29 12:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20250722_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='reported_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlistitem',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
