# Generated by Django 4.0.8 on 2026-03-17 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlistitem',
            name='reported_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
