# Generated by Django 4.0.8 on 2024-09-18 11:29

from django.db import migrations, models
from django.db.models.functions import Concat


def update_anchor(apps, schema_editor):
    Occurence = apps.get_model('references', 'Occurence')
    Occurence.objects.filter(anchor='').update(
        anchor=Concat(models.Value('sec'), 'section')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_occurence_anchor'),
    ]

    operations = [
        migrations.RunPython(update_anchor, migrations.RunPython.noop)
    ]
