# Generated by Django 4.0.8 on 2025-08-22 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmark_deleted_bookmark_reported_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='audio_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='mode',
            field=models.CharField(choices=[('text', 'text'), ('audio', 'audio')], default='text', max_length=64),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='reported_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
