# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20190416_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payuorder',
            name='amount',
        ),
    ]
