# Generated by Django 2.2.5 on 2019-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_fix_notification_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payucardtoken',
            options={'verbose_name': 'PayU card token', 'verbose_name_plural': 'PayU card tokens'},
        ),
        migrations.AlterModelOptions(
            name='payunotification',
            options={'verbose_name': 'PayU notification', 'verbose_name_plural': 'PayU notifications'},
        ),
        migrations.AlterModelOptions(
            name='payuorder',
            options={'verbose_name': 'PayU order', 'verbose_name_plural': 'PayU orders'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='payed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payed at'),
        ),
        migrations.AlterField(
            model_name='payucardtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='payucardtoken',
            name='disposable_token',
            field=models.CharField(max_length=255, verbose_name='disposable token'),
        ),
        migrations.AlterField(
            model_name='payucardtoken',
            name='pos_id',
            field=models.CharField(max_length=255, verbose_name='POS id'),
        ),
        migrations.AlterField(
            model_name='payucardtoken',
            name='reusable_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reusable token'),
        ),
        migrations.AlterField(
            model_name='payunotification',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='payunotification',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='received_at'),
        ),
        migrations.AlterField(
            model_name='payuorder',
            name='customer_ip',
            field=models.GenericIPAddressField(verbose_name='customer IP'),
        ),
        migrations.AlterField(
            model_name='payuorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='order ID'),
        ),
        migrations.AlterField(
            model_name='payuorder',
            name='pos_id',
            field=models.CharField(max_length=255, verbose_name='POS id'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='method',
            field=models.CharField(choices=[('payu-re', 'PayU (płatność odnawialna)'), ('payu', 'PayU')], max_length=255, verbose_name='method'),
        ),
    ]
