# Generated by Django 2.2.6 on 2019-11-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_populate_payed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.IntegerField(verbose_name='minimum amount')),
                ('min_for_year', models.IntegerField(verbose_name='minimum amount for year')),
                ('single_amounts', models.CharField(max_length=255, verbose_name='proposed amounts for single payment')),
                ('monthly_amounts', models.CharField(max_length=255, verbose_name='proposed amounts for monthly payments')),
            ],
        ),
    ]
