# Generated by Django 2.2.6 on 2019-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='monthly',
            field=models.BooleanField(default=False, verbose_name='monthly'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='yearly',
            field=models.BooleanField(default=False, verbose_name='yearly'),
        ),
    ]
