# Generated by Django 2.2.6 on 2019-11-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_migrate_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='default_monthly_amount',
            field=models.IntegerField(default=10, verbose_name='default monthly amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='default_single_amount',
            field=models.IntegerField(default=100, verbose_name='default single amount'),
            preserve_default=False,
        ),
    ]
