# Generated by Django 2.2.6 on 2019-11-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_auto_20191127_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
