# Generated by Django 2.2.6 on 2019-11-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_auto_20191127_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='method',
        ),
    ]
