# Generated by Django 2.2.6 on 2019-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_auto_20191127_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambassador',
            options={'ordering': ['name'], 'verbose_name': 'ambassador', 'verbose_name_plural': 'ambassadors'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'club', 'verbose_name_plural': 'clubs'},
        ),
        migrations.AddField(
            model_name='ambassador',
            name='text',
            field=models.CharField(default='', max_length=1024, verbose_name='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo'),
        ),
    ]
