# Generated by Django 2.2.9 on 2020-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_auto_20191127_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='payuorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
