# Generated by Django 2.2.16 on 2020-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0023_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='honorary',
            new_name='manual',
        ),
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.CharField(blank=True, max_length=2048, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
