# Generated by Django 2.2.19 on 2021-06-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0026_schedule_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Membership', verbose_name='membership'),
        ),
    ]
