# Generated by Django 2.2.19 on 2021-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0027_auto_20210609_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last name')),
                ('sex', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='sex')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('building', models.CharField(blank=True, max_length=255, verbose_name='building')),
                ('flat', models.CharField(blank=True, max_length=255, verbose_name='flat')),
                ('town', models.CharField(blank=True, max_length=255, verbose_name='town')),
                ('postal_code', models.CharField(blank=True, max_length=255, verbose_name='postal code')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='e-mail')),
                ('iban', models.CharField(blank=True, max_length=255, verbose_name='IBAN')),
                ('payment_id', models.CharField(blank=True, max_length=255, verbose_name='payment identifier')),
                ('agree_newsletter', models.BooleanField(verbose_name='agree newsletter')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
            options={
                'verbose_name': 'direct debit',
                'verbose_name_plural': 'direct debits',
            },
        ),
    ]
