# Generated by Django 2.2.19 on 2021-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0028_directdebit'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='method',
            field=models.CharField(choices=[('payu-re', 'payu-re'), ('payu', 'payu'), ('paypal', 'paypal')], default='', max_length=32, verbose_name='method'),
            preserve_default=False,
        ),
    ]
