# Generated by Django 2.2.19 on 2021-07-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0031_auto_20210622_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=2048)),
                ('required', models.BooleanField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='consent',
            field=models.ManyToManyField(to='club.Consent'),
        ),
    ]
