# Generated by Django 2.2.19 on 2021-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0032_auto_20210730_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='postal',
            field=models.TextField(blank=True),
        ),
    ]
