# Generated by Django 2.2.19 on 2021-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0034_auto_20210730_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='postal_town',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
