# Generated by Django 2.2.19 on 2021-07-30 12:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0035_schedule_postal_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='postal_1',
            new_name='postal',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='postal_2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='postal_3',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='postal_4',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='postal_country',
            field=django_countries.fields.CountryField(blank=True, default='PL', max_length=2),
        ),
    ]
