# Generated by Django 2.2.19 on 2021-09-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0036_auto_20210730_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectDebit',
        ),
    ]
