# Generated by Django 2.2.27 on 2022-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0037_delete_directdebit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payuorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
