# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'katalog', 'verbose_name_plural': 'katalogi'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'biblioteka', 'verbose_name_plural': 'biblioteki'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nazwa'),
        ),
    ]
