# Generated by Django 2.2.5 on 2019-09-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('club-membership-expiring', 'club membership expiring'), ('club-payment-unfinished', 'club payment unfinished')], help_text='?', max_length=128, verbose_name='state')),
                ('subject', models.CharField(max_length=1024, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('days', models.SmallIntegerField(blank=True, null=True, verbose_name='days')),
                ('hour', models.IntegerField(blank=True, null=True, verbose_name='hour')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
            },
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=1024, verbose_name='e-mail')),
                ('subject', models.CharField(max_length=1024, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.EmailTemplate')),
            ],
            options={
                'verbose_name': 'email sent',
                'verbose_name_plural': 'emails sent',
                'ordering': ('-timestamp',),
            },
        ),
    ]
