# Generated by Django 2.2.9 on 2020-01-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20200128_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='key',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Would-be donor'), (30, 'One-time donor'), (40, 'Recurring donor'), (10, 'Cold'), (50, 'Opt out')]),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_1',
            field=models.BooleanField(default=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_2',
            field=models.BooleanField(default=True, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_3',
            field=models.BooleanField(default=True, verbose_name='Wednesday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_4',
            field=models.BooleanField(default=True, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_5',
            field=models.BooleanField(default=True, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_6',
            field=models.BooleanField(default=True, verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_7',
            field=models.BooleanField(default=True, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='max_days_since',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='max days since'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='min_days_since',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='min days since'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='state',
            field=models.CharField(choices=[('cold', 'cold group'), ('club-payment-unfinished', 'club would-be donors'), ('club-single', 'club one-time donors'), ('club-membership-expiring', 'club one-time donors with donation expiring'), ('club-recurring', 'club recurring donors'), ('club-recurring-payment-problem', 'club recurring donors with donation expired')], help_text='?', max_length=128, verbose_name='state'),
        ),
    ]
