# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20201126_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'kontakt', 'verbose_name_plural': 'kontakty'},
        ),
        migrations.AlterModelOptions(
            name='emailsent',
            options={'ordering': ('-timestamp',), 'verbose_name': 'wysłany e-mail', 'verbose_name_plural': 'wysłane e-maile'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'szablon e-maila', 'verbose_name_plural': 'szablony e-maili'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Lodówka'), (20, 'Niedoszły darczyńca'), (30, 'Darczyńca z jednorazową wpłatą'), (40, 'Darczyńca z wpłatą cykliczną'), (45, 'Członkostwo ustawione ręcznie'), (50, 'Opt out')]),
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='body',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='subject',
            field=models.CharField(max_length=1024, verbose_name='temat'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_1',
            field=models.BooleanField(default=True, verbose_name='poniedziałek'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_2',
            field=models.BooleanField(default=True, verbose_name='wtorek'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_3',
            field=models.BooleanField(default=True, verbose_name='środa'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_4',
            field=models.BooleanField(default=True, verbose_name='czwartek'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_5',
            field=models.BooleanField(default=True, verbose_name='piątek'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_6',
            field=models.BooleanField(default=True, verbose_name='sobota'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='dow_7',
            field=models.BooleanField(default=True, verbose_name='niedziela'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='aktywny'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='max_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='do dnia miesiąca'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='max_days_since',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='dni po, do'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='max_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='do godziny'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='min_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='od dnia miesiąca'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='min_days_since',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='dni po, od'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='min_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='od godziny'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='state',
            field=models.CharField(choices=[('cold', 'lodówka'), ('club-payment-unfinished', 'niedoszli darczyńcy'), ('club-single', 'darczyńcy z jednorazową wpłatą'), ('club-membership-expiring', 'darczyńcy z wygasającą jednorazową wpłatą'), ('club-recurring', 'darczyńcy z wpłatą cykliczną'), ('club-recurring-payment-problem', 'darczyńcy z wygasającą wpłatą cykliczną')], help_text='?', max_length=128, verbose_name='stan'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=1024, verbose_name='temat'),
        ),
    ]
