# Generated by Django 2.2.5 on 2019-09-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
