# Generated by Django 4.0.8 on 2024-11-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bookuserdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.consumer'),
        ),
    ]
