# Generated by Django 2.2.9 on 2019-12-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_book_preview_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='findable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='findable'),
        ),
    ]
