# Generated by Django 2.2.10 on 2020-04-03 09:40

import catalogue.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_book_findable'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_ebookpoint',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=catalogue.fields.UploadToPath('book/cover_ebookpoint/%s.jpg'), verbose_name='cover for Ebookpoint'),
        ),
    ]
