# Generated by Django 2.2.10 on 2020-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_book_cover_ebookpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_api_thumb_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_ebookpoint_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_thumb_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='epub_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='fb2_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='html_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='mobi_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='simple_cover_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='txt_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
    ]
