# Generated by Django 2.2.16 on 2020-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20200414_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='role',
            field=models.CharField(blank=True, choices=[('', '–'), ('recommend', 'recommended')], db_index=True, max_length=128),
        ),
    ]
