# Generated by Django 2.2.16 on 2021-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_collection_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmedia',
            options={'ordering': ('type', 'index'), 'verbose_name': 'book media', 'verbose_name_plural': 'book media'},
        ),
        migrations.AddField(
            model_name='bookmedia',
            name='project_description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='bookmedia',
            name='project_icon',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
