# Generated by Django 2.2.25 on 2022-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_collection_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='catalogue/tag/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='photo_attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
