# Generated by Django 2.2.25 on 2022-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_bookmedia_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='toc',
            field=models.TextField(blank=True, verbose_name='toc'),
        ),
    ]
