# Generated by Django 2.2.28 on 2022-09-30 08:50

import catalogue.fields
from django.db import migrations
import fnpdjango.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20220928_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=catalogue.fields.CoverField('cover', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_api_thumb',
            field=catalogue.fields.CoverApiThumbField('cover thumbnail for mobile app'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_clean',
            field=catalogue.fields.CoverCleanField('clean cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_ebookpoint',
            field=catalogue.fields.CoverEbookpointField('cover for Ebookpoint'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_thumb',
            field=catalogue.fields.CoverThumbField('cover thumbnail'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=catalogue.fields.EpubField(storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_file',
            field=catalogue.fields.Fb2Field(storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='html_file',
            field=catalogue.fields.HtmlField(storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobi_file',
            field=catalogue.fields.MobiField(storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=catalogue.fields.PdfField(storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='simple_cover',
            field=catalogue.fields.SimpleCoverField('cover for mobile app'),
        ),
        migrations.AlterField(
            model_name='book',
            name='txt_file',
            field=catalogue.fields.TxtField(storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='xml_file',
            field=catalogue.fields.XmlField(storage=fnpdjango.storage.BofhFileSystemStorage(), with_etag=False),
        ),
    ]
