# Generated by Django 2.2.28 on 2022-09-30 08:50

import catalogue.fields
from django.db import migrations
import fnpdjango.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20220928_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=catalogue.fields.CoverField('cover', etag_field_name='cover_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_api_thumb',
            field=catalogue.fields.CoverApiThumbField('cover thumbnail for mobile app', etag_field_name='cover_api_thumb_etag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_clean',
            field=catalogue.fields.CoverCleanField('clean cover', etag_field_name='cover_clean_etag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_ebookpoint',
            field=catalogue.fields.CoverEbookpointField('cover for Ebookpoint', etag_field_name='cover_ebookpoint_etag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_thumb',
            field=catalogue.fields.CoverThumbField('cover thumbnail', etag_field_name='cover_thumb_etag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=catalogue.fields.EpubField(etag_field_name='epub_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='fb2_file',
            field=catalogue.fields.Fb2Field(etag_field_name='fb2_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='html_file',
            field=catalogue.fields.HtmlField(etag_field_name='html_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobi_file',
            field=catalogue.fields.MobiField(etag_field_name='mobi_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=catalogue.fields.PdfField(etag_field_name='pdf_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='simple_cover',
            field=catalogue.fields.SimpleCoverField('cover for mobile app', etag_field_name='simple_cover_etag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='txt_file',
            field=catalogue.fields.TxtField(etag_field_name='txt_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AlterField(
            model_name='book',
            name='xml_file',
            field=catalogue.fields.XmlField(storage=fnpdjango.storage.BofhFileSystemStorage(), with_etag=False),
        ),
    ]
