# Generated by Django 4.0.8 on 2022-10-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20220930_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='authors',
            field=models.ManyToManyField(limit_choices_to={'category': 'author'}, to='catalogue.tag'),
        ),
    ]
