# Generated by Django 4.0.8 on 2022-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='authors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'author'}, to='catalogue.tag'),
        ),
    ]
