# Generated by Django 4.0.8 on 2022-11-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_alter_collection_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='adjective_feminine_singular',
            field=models.CharField(blank=True, help_text='twórczość … Adama Mickiewicza; dotyczy epok', max_length=255, verbose_name='przymiotnik pojedynczy żeński'),
        ),
        migrations.AddField(
            model_name='tag',
            name='adjective_nonmasculine_plural',
            field=models.CharField(blank=True, help_text='utwory … Adama Mickiewicza; dotyczy epok', max_length=255, verbose_name='przymiotnik mnogi niemęskoosobowy'),
        ),
        migrations.AddField(
            model_name='tag',
            name='collective_noun',
            field=models.CharField(blank=True, help_text='np. „Liryka” albo „Twórczość dramatyczna”; dotyczy rodzajów', max_length=255, verbose_name='określenie zbiorowe'),
        ),
        migrations.AddField(
            model_name='tag',
            name='genitive',
            field=models.CharField(blank=True, help_text='utwory … (czyje?); dotyczy autorów', max_length=255, verbose_name='dopełniacz'),
        ),
        migrations.AddField(
            model_name='tag',
            name='genre_epoch_specific',
            field=models.BooleanField(default=False, help_text='Po wskazaniu tego gatunku, dodanie epoki byłoby nadmiarowe, np. „dramat romantyczny”'),
        ),
        migrations.AddField(
            model_name='tag',
            name='plural',
            field=models.CharField(blank=True, help_text='dotyczy gatunków', max_length=255, verbose_name='liczba mnoga'),
        ),
    ]
