# Generated by Django 4.0.8 on 2023-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_tag_adjective_feminine_singular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='type',
            field=models.CharField(choices=[('mp3', 'MP3 file'), ('ogg', 'Ogg Vorbis file'), ('daisy', 'DAISY file'), ('audio.epub', 'EPUB+audio file'), ('sync', 'sync file')], db_index=True, max_length=20, verbose_name='type'),
        ),
    ]
