# Generated by Django 4.0.8 on 2023-06-02 13:08

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_snippet'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snippet',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='search_vector_idx'),
        ),
    ]
