# Generated by Django 4.0.8 on 2023-08-28 14:36

import catalogue.fields
import catalogue.models.bookmedia
from django.db import migrations, models
import django.db.models.deletion
import fnpdjango.storage


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalogue', '0045_snippet_search_vector_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('sort_key_author', 'sort_key'), 'verbose_name': 'książka', 'verbose_name_plural': 'książki'},
        ),
        migrations.AlterModelOptions(
            name='bookmedia',
            options={'ordering': ('type', 'index'), 'verbose_name': 'media książki', 'verbose_name_plural': 'media książek'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('title',), 'verbose_name': 'kolekcja', 'verbose_name_plural': 'kolekcje'},
        ),
        migrations.AlterModelOptions(
            name='fragment',
            options={'ordering': ('book', 'anchor'), 'verbose_name': 'fragment', 'verbose_name_plural': 'fragmenty'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('netloc',), 'verbose_name': 'źródło', 'verbose_name_plural': 'źródła'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('sort_key',), 'verbose_name': 'tag', 'verbose_name_plural': 'tagi'},
        ),
        migrations.AlterField(
            model_name='book',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='abstrakt'),
        ),
        migrations.AlterField(
            model_name='book',
            name='audio_length',
            field=models.CharField(blank=True, max_length=8, verbose_name='długość audio'),
        ),
        migrations.AlterField(
            model_name='book',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='data motyfikacji'),
        ),
        migrations.AlterField(
            model_name='book',
            name='common_slug',
            field=models.SlugField(max_length=120, verbose_name='wspólny slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=catalogue.fields.CoverField(etag_field_name='cover_etag', storage=fnpdjango.storage.BofhFileSystemStorage(), verbose_name='okładka'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_api_thumb',
            field=catalogue.fields.CoverApiThumbField(etag_field_name='cover_api_thumb_etag', verbose_name='mniaturka okładki dla aplikacji'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_clean',
            field=catalogue.fields.CoverCleanField(etag_field_name='cover_clean_etag', verbose_name='czysta okładka'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_ebookpoint',
            field=catalogue.fields.CoverEbookpointField(etag_field_name='cover_ebookpoint_etag', verbose_name='okładka dla Ebookpoint'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_thumb',
            field=catalogue.fields.CoverThumbField(etag_field_name='cover_thumb_etag', verbose_name='miniatura okładki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='book',
            name='extra_info',
            field=models.TextField(default='{}', verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='book',
            name='findable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='wyszukiwalna'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(db_index=True, default='pol', max_length=3, verbose_name='kod języka'),
        ),
        migrations.AlterField(
            model_name='book',
            name='parent_number',
            field=models.IntegerField(default=0, verbose_name='numer w ramach rodzica'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.BooleanField(default=False, verbose_name='prapremiera'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview_until',
            field=models.DateField(blank=True, null=True, verbose_name='prapremiera do'),
        ),
        migrations.AlterField(
            model_name='book',
            name='print_on_demand',
            field=models.BooleanField(default=False, verbose_name='druk na żądanie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='polecane'),
        ),
        migrations.AlterField(
            model_name='book',
            name='simple_cover',
            field=catalogue.fields.SimpleCoverField(etag_field_name='simple_cover_etag', verbose_name='okładka dla aplikacji'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sort_key',
            field=models.CharField(db_index=True, editable=False, max_length=120, verbose_name='klucz sortowania'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sort_key_author',
            field=models.CharField(db_index=True, default='', editable=False, max_length=120, verbose_name='klucz sortowania wg autora'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32767, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='book',
            name='toc',
            field=models.TextField(blank=True, verbose_name='spis treści'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='extra_info',
            field=models.TextField(default='{}', editable=False, verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='file',
            field=models.FileField(max_length=600, storage=fnpdjango.storage.BofhFileSystemStorage(), upload_to=catalogue.models.bookmedia._file_upload_to, verbose_name='plik'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='index',
            field=models.IntegerField(default=0, verbose_name='indeks'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='name',
            field=models.CharField(max_length=512, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='part_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='nazwa części'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='type',
            field=models.CharField(choices=[('mp3', 'plik MP3'), ('ogg', 'plik Ogg Vorbis'), ('daisy', 'plik DAISY'), ('audio.epub', 'plik EPUB+audio'), ('sync', 'plik sync')], db_index=True, max_length=20, verbose_name='typ'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='book_slugs',
            field=models.TextField(verbose_name='slugi książek'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[('book', 'książki'), ('picture', 'obrazy')], db_index=True, default='book', max_length=10, verbose_name='rodzaj'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='listed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='na liście'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='role',
            field=models.CharField(blank=True, choices=[('', '–'), ('recommend', 'polecane')], db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(db_index=True, max_length=120, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_de',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_en',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_es',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_fr',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_it',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_lt',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_pl',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_uk',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_es',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_fr',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_it',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_lt',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_pl',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='source',
            name='netloc',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='położenie sieciowe'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('author', 'autor'), ('epoch', 'epoka'), ('kind', 'rodzaj'), ('genre', 'gatunek'), ('theme', 'motyw'), ('set', 'półka'), ('thing', 'obiekt')], db_index=True, max_length=50, verbose_name='kategoria'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_de',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_es',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_it',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_lt',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_pl',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=120, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sort_key',
            field=models.CharField(db_index=True, max_length=120, verbose_name='klucz sortowania'),
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='typ obiektu'),
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='id obiektu'),
        ),
    ]
