# Generated by Django 4.0.8 on 2024-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_alter_book_options_alter_bookmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(to='catalogue.tag'),
        ),
    ]
