# Generated by Django 4.0.8 on 2024-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_book_translators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='for_books',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='for_pictures',
        ),
        migrations.AlterField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, to='catalogue.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('author', 'autor'), ('epoch', 'epoka'), ('kind', 'rodzaj'), ('genre', 'gatunek'), ('theme', 'motyw'), ('set', 'półka')], db_index=True, max_length=50, verbose_name='kategoria'),
        ),
    ]
