# Generated by Django 4.0.8 on 2024-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_remove_collection_kind_remove_tag_for_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='anchor',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
