# Generated by Django 4.0.8 on 2025-02-26 14:46

import catalogue.fields
from django.db import migrations, models
import fnpdjango.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_remove_collection_kind_remove_tag_for_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='html_nonotes_file',
            field=catalogue.fields.HtmlNonotesField(etag_field_name='html_nonotes_file_etag', storage=fnpdjango.storage.BofhFileSystemStorage()),
        ),
        migrations.AddField(
            model_name='book',
            name='html_nonotes_file_etag',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='license',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='licencja'),
        ),
    ]
