# Generated by Django 4.0.8 on 2025-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_book_html_nonotes_file_book_html_nonotes_file_etag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='narrators',
            field=models.ManyToManyField(blank=True, related_name='narrated', to='catalogue.tag'),
        ),
    ]
