# Generated by Django 4.0.8 on 2025-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_book_narrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
    ]
