# Generated by Django 4.0.8 on 2026-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_book_has_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='read_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
