# Generated by Django 4.0.8 on 2026-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_book_pages_book_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
