# Generated by Django 4.0.8 on 2026-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_alter_book_pages_alter_book_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sort_key',
            field=models.CharField(db_collation='C', db_index=True, editable=False, max_length=120, verbose_name='klucz sortowania'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sort_key_author',
            field=models.CharField(db_collation='C', db_index=True, default='', editable=False, max_length=120, verbose_name='klucz sortowania wg autora'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sort_key',
            field=models.CharField(db_collation='C', db_index=True, max_length=120, verbose_name='klucz sortowania'),
        ),
    ]
