# Generated by Django 4.0.8 on 2026-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_alter_book_sort_key_alter_book_sort_key_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='can_sell',
            field=models.BooleanField(default=True, verbose_name='do sprzedaży'),
        ),
    ]
