# Generated by Django 4.0.8 on 2026-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_book_can_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_mp3',
            field=models.CharField(blank=True, max_length=32, verbose_name='ISBN audiobooka'),
        ),
    ]
