# Generated by Django 4.0.8 on 2026-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_book_isbn_mp3'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='can_sell_mp3',
            field=models.BooleanField(default=True, verbose_name='do sprzedaży mp3'),
        ),
    ]
