# Generated by Django 4.0.8 on 2026-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_book_can_sell_mp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='can_sell_mp3',
            field=models.BooleanField(default=False, verbose_name='do sprzedaży mp3'),
        ),
    ]
