# Generated by Django 2.2.19 on 2021-06-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0031_auto_20210622_0945'),
        ('paypal', '0003_auto_20190729_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingagreement',
            name='user',
        ),
        migrations.AddField(
            model_name='billingagreement',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='club.Schedule'),
            preserve_default=False,
        ),
    ]
