# Generated by Django 4.0.8 on 2026-04-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0004_auto_20210622_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypal.billingagreement')),
            ],
        ),
    ]
