# Generated by Django 2.2.16 on 2021-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_auto_20190729_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='long_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='long name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='perk',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
