# Generated by Django 2.2.28 on 2022-10-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_funding_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['-completed_at', 'pk'], 'verbose_name': 'funding', 'verbose_name_plural': 'fundings'},
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='payed_at',
            new_name='completed_at',
        ),
    ]
