# Generated by Django 2.2.28 on 2022-10-03 10:55
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0008_auto_20221003_1235'),
    ]

    # migration intentionally left empty
    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
            elidable=True
        )
    ]
