# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_options_alter_pollitem_options_and_more'),
        ('catalogue', '0046_alter_book_options_alter_bookmedia_options_and_more'),
        ('funding', '0009_move_from_getpaid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['-completed_at', 'pk'], 'verbose_name': 'wpłata', 'verbose_name_plural': 'wpłaty'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-end'], 'verbose_name': 'zbiórka', 'verbose_name_plural': 'zbiórki'},
        ),
        migrations.AlterModelOptions(
            name='payunotification',
            options={'verbose_name': 'notyfikacja PayU', 'verbose_name_plural': 'notyfikacje PayU'},
        ),
        migrations.AlterModelOptions(
            name='perk',
            options={'ordering': ['-price'], 'verbose_name': 'prezent', 'verbose_name_plural': 'prezenty'},
        ),
        migrations.AlterModelOptions(
            name='spent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'pieniądze wydane na książkę', 'verbose_name_plural': 'pieniądze wydane na książki'},
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='customer_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='adres IP'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='name',
            field=models.CharField(blank=True, max_length=127, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='notifications',
            field=models.BooleanField(db_index=True, default=True, verbose_name='powiadomienia'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funding.offer', verbose_name='zbiórka'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID zamówienia'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='perks',
            field=models.ManyToManyField(blank=True, to='funding.perk', verbose_name='prezenty'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Czeka'), ('WAITING_FOR_CONFIRMATION', 'Czeka na potwierdzenie'), ('COMPLETED', 'Ukończone'), ('CANCELED', 'Anulowane'), ('REJECTED', 'Odrzucone'), ('ERR-INVALID_TOKEN', 'Błędny token')], max_length=128),
        ),
        migrations.AlterField(
            model_name='offer',
            name='author',
            field=models.CharField(max_length=255, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Opublikowana książka.', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.book'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cover',
            field=models.ImageField(upload_to='funding/covers', verbose_name='Okładka'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end',
            field=models.DateField(db_index=True, verbose_name='koniec'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='notified_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wysłano powiadomienia o zakończeniu'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='notified_near',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wysłano powiadomienia przed końcem'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='poll',
            field=models.ForeignKey(blank=True, help_text='Ankieta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='redakcja_url',
            field=models.URLField(blank=True, verbose_name='URL na Redakcji'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start',
            field=models.DateField(db_index=True, verbose_name='początek'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota docelowa'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='payunotification',
            name='body',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='payunotification',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='odebrana'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data końcowa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name',
            field=models.CharField(max_length=255, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='long_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='długa nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.offer', verbose_name='zbiórka'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='timestamp',
            field=models.DateField(verbose_name='kiedy'),
        ),
    ]
