# Generated by Django 4.0.8 on 2024-01-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_alter_funding_options_alter_offer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='customer_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='notify_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='funding',
            name='pos_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='POS id'),
        ),
    ]
