# Generated by Django 4.0.8 on 2024-02-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_alter_book_options_alter_bookmedia_options_and_more'),
        ('funding', '0011_alter_funding_customer_ip_alter_funding_notify_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='annotation',
            field=models.CharField(blank=True, help_text="np. 'audiobook'", max_length=255, verbose_name='adnotacja'),
        ),
        migrations.AddField(
            model_name='spent',
            name='link',
            field=models.URLField(blank=True, help_text='zamiast książki, np. kolekcja'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.book'),
        ),
    ]
