# Generated by Django 2.2.6 on 2019-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='open_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='place',
            field=models.SlugField(choices=[('top', 'Top of all pages.'), ('book-page', 'Book page'), ('book-text-intermission', 'Book text intermission'), ('book-fragment-list', 'Next to list of book fragments.')]),
        ),
    ]
