# Generated by Django 2.2.6 on 2019-12-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0004_auto_20191211_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_es',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_fr',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_it',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_lt',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_pl',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='dynamictextinsert',
            name='text_uk',
        ),
        migrations.AlterField(
            model_name='banner',
            name='action_label',
            field=models.CharField(blank=True, help_text='', max_length=255),
        ),
        migrations.CreateModel(
            name='DynamicTextInsertText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=10)),
                ('text_color', models.CharField(blank=True, max_length=10)),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annoy.DynamicTextInsert')),
            ],
        ),
    ]
