# Generated by Django 2.2.6 on 2019-12-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0006_auto_20191213_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.FileField(blank=True, upload_to='annoy/banners/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='action_label',
            field=models.CharField(blank=True, help_text='If empty, whole banner will serve as a link', max_length=255, verbose_name='action label'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='close_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='close label'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='open_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='open label'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='place',
            field=models.SlugField(choices=[('top', 'Top of all pages.'), ('book-page', 'Book page'), ('book-text-intermission', 'Book text intermission'), ('book-fragment-list', 'Next to list of book fragments.'), ('blackout', 'Blackout')], verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Banners with higher priority come first.', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='show_members',
            field=models.BooleanField(default=False, verbose_name='show members'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='since'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='staff_preview',
            field=models.BooleanField(default=False, verbose_name='staff preview'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_de',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_es',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_fr',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_it',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_lt',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_pl',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='until'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='dynamictextinserttext',
            name='image',
            field=models.FileField(blank=True, upload_to='annoy/inserts/'),
        ),
    ]
