# Generated by Django 2.2.6 on 2019-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0007_auto_20191216_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictextinserttext',
            name='own_colors',
            field=models.BooleanField(default=False),
        ),
    ]
