# Generated by Django 2.2.19 on 2021-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0008_dynamictextinserttext_own_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='style',
            field=models.CharField(blank=True, choices=[('blackout_full', 'Full screen'), ('blackout_centre', 'Centre of screen'), ('blackout_upper', 'Upper half of screen')], help_text='Affects blackout.', max_length=255, verbose_name='style'),
        ),
    ]
