# Generated by Django 2.2.19 on 2021-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0009_banner_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='smallfont',
            field=models.BooleanField(default=False, verbose_name='small font'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='style',
            field=models.CharField(blank=True, choices=[('blackout_full', 'Full screen'), ('blackout_upper', 'Upper half of screen')], help_text='Affects blackout.', max_length=255, verbose_name='style'),
        ),
    ]
