# Generated by Django 2.2.27 on 2022-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0011_auto_20210610_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='only_authenticated',
            field=models.BooleanField(default=False, verbose_name='only for authenticated users'),
        ),
    ]
