# Generated by Django 4.0.8 on 2023-07-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0012_banner_only_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaInsertSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('epub', 'epub'), ('mobi', 'mobi')], max_length=8)),
                ('etag', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MediaInsertText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('text', models.TextField()),
                ('media_insert_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annoy.mediainsertset')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
