# Generated by Django 4.0.8 on 2024-08-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0015_alter_banner_options_alter_dynamictextinsert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediainsertset',
            name='file_format',
            field=models.CharField(choices=[('epub', 'epub'), ('mobi', 'mobi'), ('pdf', 'pdf')], max_length=8),
        ),
    ]
