# Generated by Django 4.0.8 on 2024-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0016_alter_mediainsertset_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='postęp'),
        ),
        migrations.AddField(
            model_name='banner',
            name='target',
            field=models.IntegerField(blank=True, null=True, verbose_name='cel'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='place',
            field=models.SlugField(choices=[('top', 'U góry wszystkich stron'), ('book-page', 'Strona książki'), ('book-text-intermission', 'Przerwa w treści książki'), ('book-fragment-list', 'Obok listy fragmentów książki'), ('blackout', 'Blackout'), ('crisis', 'Kryzysowa')], verbose_name='miejsce'),
        ),
    ]
