# Generated by Django 4.0.8 on 2025-11-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_book_has_audio'),
        ('annoy', '0018_alter_banner_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dla zespołu', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='annoy/banners/', verbose_name='obraz')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='books',
            field=models.ManyToManyField(blank=True, to='catalogue.book'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='place',
            field=models.SlugField(choices=[('top', 'U góry wszystkich stron'), ('book-page', 'Strona książki'), ('book-page-center', 'Strona książki, środek'), ('book-text-intermission', 'Przerwa w treści książki'), ('book-fragment-list', 'Obok listy fragmentów książki'), ('blackout', 'Blackout'), ('crisis', 'Kryzysowa')], verbose_name='miejsce'),
        ),
        migrations.AddField(
            model_name='banner',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='annoy.campaign'),
        ),
    ]
