# Generated by Django 4.0.8 on 2026-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0019_campaign_banner_books_alter_banner_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='landing',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Kampanie z wyższym priorytetem mają pierwszeństwo.', verbose_name='priorytet'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='postęp'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target',
            field=models.IntegerField(blank=True, null=True, verbose_name='cel'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='place',
            field=models.SlugField(choices=[('top', 'U góry wszystkich stron'), ('book-page', 'Strona książki'), ('book-page-center', 'Strona książki, środek'), ('book-text-intermission', 'Przerwa w treści książki'), ('book-fragment-list', 'Obok listy fragmentów książki'), ('blackout', 'Blackout'), ('crisis', 'Kryzysowa'), ('seasonal', 'Sezonowa')], verbose_name='miejsce'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='Wewnętrzna nazwa kampanii', max_length=255),
        ),
    ]
