# Generated by Django 4.0.8 on 2026-03-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoy', '0021_campaign_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='target',
        ),
    ]
