# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0003_auto_20190729_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishingsuggestion',
            options={'ordering': ('-created_at',), 'verbose_name': 'sugestia publikacji', 'verbose_name_plural': 'sugestie publikacji'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ('-created_at',), 'verbose_name': 'sugestia', 'verbose_name_plural': 'sugestie'},
        ),
        migrations.AlterField(
            model_name='publishingsuggestion',
            name='audiobooks',
            field=models.TextField(blank=True, null=True, verbose_name='audiobooki'),
        ),
        migrations.AlterField(
            model_name='publishingsuggestion',
            name='books',
            field=models.TextField(blank=True, null=True, verbose_name='książki'),
        ),
        migrations.AlterField(
            model_name='publishingsuggestion',
            name='contact',
            field=models.CharField(blank=True, max_length=120, verbose_name='kontakt'),
        ),
        migrations.AlterField(
            model_name='publishingsuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='publishingsuggestion',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='adres IP'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='contact',
            field=models.CharField(blank=True, max_length=120, verbose_name='kontakt'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='adres IP'),
        ),
    ]
