# Generated by Django 2.2.19 on 2021-09-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebit',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Date from the form', null=True, verbose_name='acquisition date'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='agree_fundraising',
            field=models.BooleanField(default=False, verbose_name='agree fundraising'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='agree_newsletter',
            field=models.BooleanField(default=False, verbose_name='agree newsletter'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pz.Campaign', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pz.Fundraiser', verbose_name='fundraiser'),
        ),
    ]
