# Generated by Django 2.2.19 on 2021-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0002_auto_20210928_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebit',
            name='iban_valid',
            field=models.BooleanField(default=False, verbose_name='IBAN valid'),
        ),
    ]
