# Generated by Django 2.2.19 on 2021-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0003_directdebit_iban_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebit',
            name='iban_valid',
            field=models.NullBooleanField(default=False, verbose_name='IBAN valid'),
        ),
    ]
