# Generated by Django 2.2.19 on 2021-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0006_bankorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebit',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelled at'),
        ),
        migrations.AlterField(
            model_name='bankorder',
            name='debits',
            field=models.ManyToManyField(blank=True, to='pz.DirectDebit'),
        ),
    ]
