# Generated by Django 2.2.19 on 2021-10-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0008_fill_cancelled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directdebit',
            name='is_cancelled',
        ),
    ]
