# Generated by Django 2.2.25 on 2022-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0009_remove_directdebit_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebit',
            name='fundraiser_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='fundraiser bonus'),
        ),
        migrations.AddField(
            model_name='directdebit',
            name='latest_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
