# Generated by Django 3.1.14 on 2022-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebit',
            name='iban_valid',
            field=models.BooleanField(default=False, null=True, verbose_name='IBAN valid'),
        ),
    ]
