# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0012_auto_20221006_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'kampania', 'verbose_name_plural': 'kampanie'},
        ),
        migrations.AlterModelOptions(
            name='directdebit',
            options={'verbose_name': 'polecenie zapłaty', 'verbose_name_plural': 'polecenia zapłaty'},
        ),
        migrations.AlterModelOptions(
            name='fundraiser',
            options={'verbose_name': 'fundraiser', 'verbose_name_plural': 'fundraiserki i fundraiserzy'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Data z formularza', null=True, verbose_name='data pozyskania'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='agree_fundraising',
            field=models.BooleanField(default=False, verbose_name='zgoda na kontakt fundraisingowy'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='agree_newsletter',
            field=models.BooleanField(default=False, verbose_name='zgoda na newsletter'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='kwota'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='bank_acceptance_date',
            field=models.DateField(blank=True, help_text='Data kiedy bank przekazał informację o akceptacji danych z formularza', null=True, verbose_name='data akceptacji przez bank'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='bank_submission_date',
            field=models.DateField(blank=True, help_text='Data przesłania danych z formularza do banku', null=True, verbose_name='data złożenia do banku'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='building',
            field=models.CharField(blank=True, max_length=255, verbose_name='nr domu'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pz.campaign', verbose_name='kampania'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anulowane'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='data urodzenia'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='flat',
            field=models.CharField(blank=True, max_length=255, verbose_name='nr mieszkania'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='fundraiser_bill',
            field=models.CharField(blank=True, max_length=255, verbose_name='nr rachunku wystawionego przez fundraisera'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='fundraiser_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='bonus fundraisera'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='fundraiser_commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='prowizja fundraisera'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='iban',
            field=models.CharField(blank=True, max_length=255, verbose_name='nr rachunku'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='iban_valid',
            field=models.BooleanField(default=False, null=True, verbose_name='prawidłowy IBAN'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='is_consumer',
            field=models.BooleanField(default=True, verbose_name='konsument'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='needs_redo',
            field=models.BooleanField(default=False, verbose_name='do powtórki'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='uwagi'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='identyfikator płatności'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'K')], max_length=1, verbose_name='płeć'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='ulica'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='submission_date',
            field=models.DateField(blank=True, help_text='Data złożenia formularza przez fundraisera', null=True, verbose_name='data dostarczenia'),
        ),
        migrations.AlterField(
            model_name='directdebit',
            name='town',
            field=models.CharField(blank=True, max_length=255, verbose_name='miejscowość'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='imię i nazwisko'),
        ),
    ]
