# Generated by Django 4.0.8 on 2024-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pz', '0013_alter_campaign_options_alter_directdebit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebit',
            name='nosignature',
            field=models.BooleanField(default=False, verbose_name='Bez podpisu'),
        ),
    ]
