# Generated by Django 2.2.10 on 2020-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160914_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('page_title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_it', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_lt', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_pl', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('phplist_id', models.IntegerField()),
            ],
        ),
    ]
