# Generated by Django 2.2.28 on 2022-10-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='crm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='phplist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
