# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20221006_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subskrypcja', 'verbose_name_plural': 'subskrypcje'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktywna'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adres e-mail'),
        ),
    ]
