# Generated by Django 4.0.8 on 2026-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sort_key',
            field=models.CharField(db_collation='C', db_index=True, max_length=128),
        ),
    ]
