# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piston', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('Nonce', 'api_nonce'),
        migrations.AlterModelTable('Consumer', 'api_consumer'),
        migrations.AlterModelTable('Token', 'api_token'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Nonce',
        ),
        migrations.RemoveField(
            model_name='token',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
