# Generated by Django 4.0.8 on 2023-08-28 14:36

import django.core.files.storage
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_auto_20160413_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('sort_key_author', 'sort_key'), 'verbose_name': 'obraz', 'verbose_name_plural': 'obrazy'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='areas_json',
            field=models.TextField(default='{}', editable=False, verbose_name='obszary w JSON'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='data zmiany'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='extra_info',
            field=models.TextField(default='{}', verbose_name='dodatkowa informacja'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='html_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/pictures/', location='/home/rczajka/for/fnp/wolnelektury/var/media/pictures'), upload_to='html', verbose_name='plik html'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_file',
            field=sorl.thumbnail.fields.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/pictures/', location='/home/rczajka/for/fnp/wolnelektury/var/media/pictures'), upload_to='images', verbose_name='plik obrazu'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='sort_key',
            field=models.CharField(db_index=True, editable=False, max_length=120, verbose_name='klucz sortowania'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='sort_key_author',
            field=models.CharField(db_index=True, default='', editable=False, max_length=120, verbose_name='klucz sortowania wg autora'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=32767, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='xml_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/pictures/', location='/home/rczajka/for/fnp/wolnelektury/var/media/pictures'), upload_to='xml', verbose_name='plik xml'),
        ),
        migrations.AlterField(
            model_name='picturearea',
            name='area',
            field=models.TextField(default='{}', editable=False, verbose_name='obszar'),
        ),
        migrations.AlterField(
            model_name='picturearea',
            name='kind',
            field=models.CharField(choices=[('thing', 'przedmiot'), ('theme', 'motyw')], db_index=True, max_length=10, verbose_name='typ'),
        ),
    ]
