# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesmianator', '0002_auto_20151221_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
