# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesmianator', '0003_auto_20190729_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuations',
            name='pickle',
            field=models.FileField(upload_to='lesmianator', verbose_name='plik kontynuacji'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='created_from',
            field=models.TextField(blank=True, null=True, verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='seen_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data ostatniego obejrzenia'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=models.TextField(verbose_name='tekst'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='view_count',
            field=models.IntegerField(default=1, verbose_name='licznik obejrzeń'),
        ),
    ]
