# Generated by Django 4.0.8 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_auto_20180831_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(max_length=2048, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, upload_to='push/img', verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=256, verbose_name='tytuł'),
        ),
    ]
