# Generated by Django 4.0.8 on 2022-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_youtubetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
